// flow-typed signature: e7f7bf469a1718d46021f917272ef846
// flow-typed version: <<STUB>>/babel-preset-es2015-node4_v^2.1.1/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-es2015-node4'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-es2015-node4' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-es2015-node4/index' {
  declare module.exports: $Exports<'babel-preset-es2015-node4'>;
}
declare module 'babel-preset-es2015-node4/index.js' {
  declare module.exports: $Exports<'babel-preset-es2015-node4'>;
}
