// flow-typed signature: 1418034d201c3e444e32df4ef11d0d1c
// flow-typed version: <<STUB>>/cash-true_v0.0.2/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cash-true'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'cash-true' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cash-true/bin/parser' {
  declare module.exports: any;
}

declare module 'cash-true/bin/true' {
  declare module.exports: any;
}

declare module 'cash-true/dist/commands/true' {
  declare module.exports: any;
}

declare module 'cash-true/dist/help/true' {
  declare module.exports: any;
}

declare module 'cash-true/dist/preparser' {
  declare module.exports: any;
}

declare module 'cash-true/dist/util/interfacer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cash-true/bin/parser.js' {
  declare module.exports: $Exports<'cash-true/bin/parser'>;
}
declare module 'cash-true/bin/true.js' {
  declare module.exports: $Exports<'cash-true/bin/true'>;
}
declare module 'cash-true/dist/commands/true.js' {
  declare module.exports: $Exports<'cash-true/dist/commands/true'>;
}
declare module 'cash-true/dist/help/true.js' {
  declare module.exports: $Exports<'cash-true/dist/help/true'>;
}
declare module 'cash-true/dist/preparser.js' {
  declare module.exports: $Exports<'cash-true/dist/preparser'>;
}
declare module 'cash-true/dist/util/interfacer.js' {
  declare module.exports: $Exports<'cash-true/dist/util/interfacer'>;
}
